version: '3.8'

services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: midcurve-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: midcurve_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U devuser -d midcurve_dev']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-dev-data:
