/**
 * Service layer input types for token CRUD operations
 * These types are used for database operations and are not shared with UI/API
 */

import type { Token } from '../../../shared/types/token.js';
import type {
  TokenConfig,
  Erc20TokenConfig,
  SolanaTokenConfig,
} from '../../../shared/types/token-config.js';

/**
 * Input type for creating a new token
 * Omits id, createdAt, updatedAt (generated by database)
 */
export type CreateTokenInput<TConfig = Record<string, unknown>> = Omit<
  Token<TConfig>,
  'id' | 'createdAt' | 'updatedAt'
>;

/**
 * Input type for updating an existing token
 * Partial updates, cannot change id, tokenType, or timestamps
 */
export type UpdateTokenInput<TConfig = Record<string, unknown>> = Partial<
  Omit<Token<TConfig>, 'id' | 'tokenType' | 'createdAt' | 'updatedAt'>
>;

/**
 * Input type aliases for creating tokens
 */
export type CreateErc20TokenInput = CreateTokenInput<Erc20TokenConfig>;
export type CreateSolanaTokenInput = CreateTokenInput<SolanaTokenConfig>;
export type CreateAnyTokenInput = CreateTokenInput<TokenConfig>;

/**
 * Input type aliases for updating tokens
 */
export type UpdateErc20TokenInput = UpdateTokenInput<Erc20TokenConfig>;
export type UpdateSolanaTokenInput = UpdateTokenInput<SolanaTokenConfig>;
export type UpdateAnyTokenInput = UpdateTokenInput<TokenConfig>;
