/**
 * Service layer input types for pool CRUD operations
 * These types are used for database operations and are not shared with UI/API
 */

import type { Pool } from '../../../shared/types/pool.js';
import type { TokenConfig } from '../../../shared/types/token-config.js';

/**
 * Input type for creating a new pool
 * Omits id, createdAt, updatedAt (generated by database)
 */
export type CreatePoolInput<
  TConfig = Record<string, unknown>,
  TState = Record<string, unknown>,
  TToken extends TokenConfig = TokenConfig
> = Omit<Pool<TConfig, TState, TToken>, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Input type for updating pool state
 * Only state can be updated (config is immutable)
 */
export type UpdatePoolStateInput<TState = Record<string, unknown>> = {
  state: TState;
};
